### ISSUE TITLE
Hi You got mistake

### ISSUE THREAD

**Issue by YasinRezvani** [uhIgnacio-zz/discord-phone#1]
Hey @uhIgnacio 
Its very bad to follow person in github after two day unfollow 
You are Not smat you are Fraudulent followers not important, skill is important
Good Luck

**Comment by uhIgnacio-zz** [comment]
Hi @YasinRezvani, today I unfollowed most of the people due to some of them we're mass following. Since they're so much I decided to mass unfollow, however if someone wants I can follow again, due to being annoying for me see `<USER> and <USER_2> started following <USER3> <TIME> ago` every time which i login to GitHub (sorry if I have bad English, I speak Spanish)
![](https://i.imgur.com/i4gDblH.png)

**Comment by uhIgnacio-zz** [comment]
Also, I don't think it is considered **fraudulent followers**, since I don't use or promote the use of API Abuse tools to gain followers or stuff like that.

**Comment by 1x6** [comment]
@YasinRezvani lmao get a life

**Comment by YasinRezvani** [comment]
Ok excuse me @uhIgnacio yes also i see programmer follow and after two days unfollow 
And send issue after block me
Nice to meet you @1x6  @uhIgnacio 
Good Luck boys

**Comment by YasinRezvani** [comment]
@uhIgnacio And one question how to add lable to issue ? (Bug , invalid, .....)
Can you learn me?
Thank you
